/* eslint-disable react/no-unescaped-entities */
import Head from "next/head";
import Image from "next/image";
import Avatar from "../components/Avatar";
import profileUrl from "../assets/profilePic.jpg";
import googleLogo from "../assets/googleLogo.png";
import { ViewGridIcon, MicrophoneIcon } from "@heroicons/react/solid";
import { SearchIcon } from "@heroicons/react/outline";
import Footer from "../components/Footer";
import { useRef } from "react";

export default function Home() {

  const searchInputRef = useRef(null);

  const search = (e) => {
    e.preventDefault();
    const term = searchInputRef.current.value;
    if (!term) {
      return;
    }
    router.push(`/search?term=${term}`);
  };

  return (
    <div>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col min-h-screen justify-between">
        {/* header */}
        <header className="flex justify-between p-5 text-sm text-gray-700">
          <div className="flex space-x-4 items-center">
            <p className="link">About</p>
            <p className="link">Store</p>
          </div>
          <div className="flex space-x-4 items-center">
            <p className="link">Gmail</p>
            <p className="link">Images</p>
            <ViewGridIcon className="h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer" />
            <Avatar url={profileUrl} />
          </div>
        </header>

        {/* body */}
        <div className="">
          <form action="" className="flex flex-col items-center">
            <div className="h-100 w-200">
              <Image
                src={googleLogo}
                height={100}
                width={300}
                objectFit="contain"
                alt="googleLogo"
              />
            </div>
            <div className="flex items-center w-full mt-5 border border-gray-200 px-5 py-3 hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full sm:max-w-xl">
              <SearchIcon className="h-5 mr-3 text-gray-500" />
              <input
                type="text"
                className="flex-grow focus:outline-none"
                ref={searchInputRef}
              />
              <MicrophoneIcon className="h-5 cursor-pointer hover:text-red-500" />
            </div>

            <div className="flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:flex-row sm:space-y-0 sm:space-x-4">
              <button className="btn" onClick={search}>
                Google Search
              </button>
              <button className="btn" onClick={search}>
                I'm Feeling Lucky
              </button>
            </div>
          </form>
        </div>
        {/* footer */}
        <Footer />
      </div>
    </div>
  );
}
